#! /bin/sh

#AutoStart applications
sxhkd &
dunst &
#polybar &
$HOME/.config/polybar/launch.sh

bspc monitor DP-2 -d 1 2 3 4
bspc monitor HDMI-0 -d 5 6 7 8

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding 	30
bspc config left_padding	 0
bspc config right_padding	 0
bspc config bottom_padding	 0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color #e84f4f
bspc config active_border_color #b8b69a

bspc rule -a Spotify desktop='^4'
bspc rule -a Firefox desktop='^5'
bspc rule -a Reaper desktop='^3'
bspc rule -a OBS desktop='^3' 
